version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: appdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://app:secret@postgres:5432/appdb
      BOT_TOKEN: ${BOT_TOKEN}
    depends_on:
      - postgres
    networks:
      - internal
      - public

  bot:
    build: ./bot
    environment:
      BACKEND_URL: http://backend:5000
      BOT_TOKEN: ${BOT_TOKEN}
    depends_on:
      - backend
    networks:
      - internal
      - public

  frontend:
    profiles:
      - production
    build: ./frontend
    volumes:
      #- ./frontend/src:/app/src
      #- ./frontend/vite.config.ts:/app/vite.config.ts
      - ./frontend/dist:/app/dist
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - VITE_API_URL=${VITE_API_URL:-http://localhost:5000/api}
    depends_on:
      - backend
    networks:
      - public
    command: sh -c "if [ \"$NODE_ENV\" = \"production\" ]; then npm run build && npx serve dist -l 3000; else npm run dev -- --host 0.0.0.0 --port 3000; fi"

networks:
  internal:
    internal: true # изолированная сеть для БД
  public:

volumes:
  pgdata:
